german = {
    'uberwacht': 'pod dohladom',
    'aneignen sich': 'privlastnit si',
    'lebendiges Wesen': 'ziva bytost',
    'auffordern': 'vyzivat',
    'das Loch': 'diera',
    'auflassen': 'rozpustit',
    'die Holle': 'peklo',
    'hinrichten': 'vykonat',
    'aufhoren': 'prestat',
    'auswendig lernen': 'ucit sa naspamat',
    'innerhalb': 'v priebehu, pocas',
    'vollziehen': 'vykonat',
    'verlassen': 'opustit',
    'das Muster': 'vzor',
    'rasch': 'rychlo',
    'ungesteuerten': 'nekontrolovatelny',
    'der Vorgang': 'proces, postup',
    'ungehindert': 'nerusene',
    'anfordern': 'ziadat',
    'stumm': 'nemy',
    'zugeteilt': 'prideleny',
    'die Bescheidenheit': 'skromnost',
    'schlicht': 'hladky, rovny',
    'begeistern': 'inspirovat',
    'berichten': 'informovat',
    'die Anleitung': 'vedenie',
    'die Veranstaltung':'podujatie',
    'enttauscht':'sklamany',
    'begegnen':'stretnut',
    'jeweils':'vzdy',
    'uberlegen':'zvazit',
    'beantragen':'ziadat',
    'Vergütung': 'odmena, nahrada',
    'der Beitrag':'prispevok',
    'die Durchfuhrung':'realizacia',
    'die Zusammenfassung':'zhrnutie',
    'die Auswertung':'vyhodnotenie',
    'die Verfolgung':'prenasledovanie',
    'mühsam':'namahave',
    'schüchtern': 'strasit',
    'allerhand': 'vselijaky',
    'die Ernährung': 'vyziva',
    'das Ausweichen': 'odreagovanie',
    'eindecken': 'zakryt',
    'ehmalig': 'byvaly',
    'erledigen': 'zariadit',
    'billiegen': 'suhlasit',
    'missachten': 'ignorovat',
    'der Vergleich': 'porovnanie',
    'anmelden': 'prihlasit',
    'die Versammlung': 'zhromazdenie',
    'das Gesetz': 'zakon',
    'äußer': 'vonkajsi',
    'hochrangig': 'vysoko postaveny',
    'Verfassung': 'ustava',
    'Gesellschaft': 'spolocnost',
    'der Grund':'dovod',
    'beschränken': 'obmedzit',
    'weitaus mehr': 'ovela viac',
    'der Umfang': 'objem',
    'das Ausmaß': 'rozsah',
    'geringen': 'minimalny',
    'die Enthüllung': 'odhalenie',
    'erschreckend': 'hrozne',
    'der Zugriff': 'pristup',
    'unbemerkten': 'nezpozorovany',
    'betreffend': 'prislusny',
    'irgendetwas': 'nieco',
    'ehemalige': 'byvaly',
    'sichtbar': 'viditelny',
    'aufgebracht': 'nahnevany',
    'erweiterte': 'rozsireny',
    'ebenfalls': 'taktiez',
    'die Verarbeitung': 'spracovanie',
    'die Laune': 'nalada',
    'ableiten': 'odvodit',
    "einflüssreich":"vplivny",
    "einprägsam":"nezabudnutelny",
    "vermeiden":"vyhnut sa",
    "überwinden":"prekonat",
    'auftreten':'vystupovat',
    'verfügen':'disponovat',
    'aufblühen':'rozkvitat',
    'die Forderung':'vyzva',
    'die Freizügigkeit':'velkorysost',
    'zufällig':'nahodny',
    'ersinnen sich':'spomenut si',
    'beschäftigen sich':'zaoberat sa',
    'erledigen':'vybavit',
    'ausführen':'vykonat',
    'zudecken':'prikrit',
    'beklagen sich':'stazovat sa',
    'erblicken':'zbadat',
    'seufzen':'vzdychat',
    'zuteilen':'pridelit',
    'das Ereignis':'udalost',
    'betreuen':'opatrovat',
    'zurzeit':'momentalne',
    'nirgends':'nikde',
    'das Wirtshaus':'krcma',
    'die Feststellung':'zalozenie',
    'bestätigen':'potvrdit',
    'der Ausichtsrat': 'dozorna rada',
    'überlegene': 'nadradeny',
    'angleichen':'zladit',
}