
english = {
    'accommodation': 'ubytovanie',
    'advert':'inzerat',
    'appointment':'vymenovanie',
    'attorney':'pravnik',
    'district':'okres',
    'enquiry':'dopyt',
    'juggle':'zonglovat',
    'obviously':'samozrejme',
    'recent':'nedavny',
    'temporary':'docastny',
    'miracle':'zazrak',
    'urgently':'surne',
    'arrive':'dorazit',
    'looking foward to': 'tesit sa',
    'keen': 'horlivy',
    'be worried': 'obavat sa',
    'compulsory': 'povinny',
    'occasion': 'prilezitosti',
    'stale': 'zatuchnuty',
    'accessories': 'doplnky',
    'cautious': 'opatrny',
    'fledg': 'uleteny',
    'attempt': 'pokus',
    'plunge': 'ponorit sa',
    'dispute':'spor',
    'assignment': 'zadanie',
    'assessment': 'hodnotenie',
    'auxillary': ' doplnujuci',
    'become': 'stat sa',
    'in addition': 'navyse',
    'know': 'vediet',
    'equivalent': 'ekvivalent',
    'polite': 'zdvorily',
    'connection': 'spojenie',
    'average': 'priemerny',
    'punch': 'uder',
    'patience': 'trpezlivost',
    'fear': 'strach', 
    'attend': 'zucastnit sa', 
    'envelope': 'obalka',
    'common': 'bezne', 
    'ancient': 'anticky', 
    'attendance': 'dochadzka', 
    'art': 'umenie', 
    'attack': 'napadnutie', 
    'illegal': 'nelegalne', 
    'convince': 'presvedcit', 
    'responsible': 'zodpovedny', 
    'sort': 'triedit',  
    'injury': 'zranenie', 
    'might': 'mozno', 
    'decision': 'rozhodnutie', 
    'coherent': 'sudrzny', 
    'equipment': 'vybavenie',  
    'occasionally': 'prilezitostne' , 
    'acquisition': 'ziskanie', 
    'behave': 'spravat sa', 
    'shout': 'kricat', 
    'gathering': 'zhromazdovanie',
    'knowledge': 'vedomost', 
    'in addition to': 'okrem toho', 
    'dependence': 'zavislost', 
    'comparable': 'porovnatelne',
    'sufficient': 'dostatocny',  
    'dozen': 'tucet', 
    'illegible': 'necitatelny', 
    'legible': 'citatelny', 
    'owner': 'vlastnik',
    'mention': 'spomenut', 
    'serious': 'seriozne', 
    'similar': 'podobne', 
    'misbehave': 'chovat sa zle', 
    'huge': 'obrovsky',  
    'occasion': 'prilezitost', 

}
